name: automerge
on:
  workflow_dispatch:
  schedule:
    - cron: '17 2,5,8,11 * * *'

jobs:
  automerge:
    uses: oclif/github-workflows/.github/workflows/automerge.yml@56d34995157cd6b3376597d9d2feb1e10af998bd # main
    secrets: inherit
